### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by steffenheyne** [chaelim/HAMT#1]
Hi,
I really would like to give your HAMT implementation a try, but using the latest master version, I get some compile errors. The main thing is that in HashTrie.h line 180/181 "m_value"  is not defined. I replaced it with m_key, but is this correct?

Also line 76 and 80 need a ";" at the end. 

I use g++ (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)

**Comment by chaelim** [comment]
Thanks for point that out. Those are all correct and for somehow I pushed the buggy version to Github. I was trying to convert to use CMake and test on Linux system but didn't have time to finish. I'll fix the bug when I push with CMake and other changes in the next time. Meanwhile, your fixes are correct and use them.
